export const phonicsLessons = [
  {
    lesson: 1,
    phoneme: 'S',
    video: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/videos/S.mp4',
    tracingImage: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/tracing/S.png',
    phonemeAudio: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/audios/S.mp3',
    examples: [
      { label: 'sun', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/sun.png' },
      { label: 'snake', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/snake.png' },
      { label: 'test', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/test.png' },
    ],
    recap: [],
    blending: [],
  },
  {
    lesson: 2,
    phoneme: 'A',
    video: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/videos/A.mp4',
    tracingImage: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/tracing/A.png',
    phonemeAudio: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/audios/A.mp3',
    examples: [
      { label: 'apple', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/apple.png' },
      { label: 'ant', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/ant.png' },
      { label: 'mat', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/mat.png' },
    ],
    recap: ['S'],
    blending: [],
  },
  {
    lesson: 3,
    phoneme: 'T',
    video: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/videos/T.mp4',
    tracingImage: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/tracing/T.png',
    phonemeAudio: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/audios/T.mp3',
    examples: [
      { label: 'tiger', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/tiger.png' },
      { label: 'rent', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/rent.png' },
      { label: 'table', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/table.png' },
    ],
    recap: ['S', 'A'],
    blending: ['as', 'at', 'sat'],
  },
  {
    lesson: 4,
    phoneme: 'P',
    video: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/videos/P.mp4',
    tracingImage: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/tracing/P.png',
    phonemeAudio: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/audios/P.mp3',
    examples: [
      { label: 'pie', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/pie.png' },
      { label: 'pen', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/pen.png' },
      { label: 'ramp', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/ramp.png' },
    ],
    recap: ['S', 'A', 'T'],
    blending: ['tap', 'pat', 'pit'],
  },
  {
    lesson: 5,
    phoneme: 'I',
    video: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/videos/I.mp4',
    tracingImage: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/tracing/I.png',
    phonemeAudio: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/audios/I.mp3',
    examples: [
      { label: 'ink', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/ink.png' },
      { label: 'inch', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/inch.png' },
      { label: 'kick', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/kick.png' },
    ],
    recap: ['S', 'A', 'T', 'P'],
    blending: ['sip', 'tip', 'pit'],
  },
  {
    lesson: 6,
    phoneme: 'N',
    video: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/videos/N.mp4',
    tracingImage: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/tracing/N.png',
    phonemeAudio: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/audios/N.mp3',
    examples: [
      { label: 'net', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/net.png' },
      { label: 'nose', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/nose.png' },
      { label: 'moon', image: 'https://ewviyxhfayxnwjurinew.supabase.co/storage/v1/object/public/phonics/samples/Group 1/moon.png' },
    ],
    recap: ['S', 'A', 'T', 'P', 'I'],
    blending: ['pin', 'nap', 'pan'],
  },
];
